version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    volumes:
      - ./database/db-definition.sql:/docker-entrypoint-initdb.d/db-definition.sql
      - ./database/db-definition.sql:/database/db-definition.sql
      - ./database/db-definition:/database/db-definition/
      - ./database/postgresql.conf:/etc/postgresql.conf

  app:
    build:
      context: ./
    restart: always
    ports:
      - 19830:3000
